# Change these first
owner: aafyyuc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AAFY PDP
    url: https://pagos.yucatan.gob.mx
  - name: AAFY Referenciados
    url: https://pagosreferencia.yucatan.gob.mx
  - name: AAFY Home
    url: https://aafy.yucatan.gob.mx
  - name: AAFY CFDI  
    url: https://srvshyws.yucatan.gob.mx/cfdi2.0/    
  - name: KIOSKOS - HOME
    url: https://recaudacion.yucatan.gob.mx
  - name: SERVICOS VUE
    method: POST
    url: https://wsaafyvue.yucatan.gob.mx/vue/services/consultar/recibos
    headers:
     - "Content-Type: application/json"
    body: '{ "cAppKey": "ghr*****", "cLineaReferencia":"121131145316911919237211275"}'
  - name: WSINGRESOS - OXXO
    method: POST
    url: https://srvshyweb.yucatan.gob.mx/cgi-bin/wspd_cgi.sh/WService=wsingresos/internet/compartido/wspagosoxxo.r
    __dangerous__insecure: true
    maxResponseTime: 2000
    headers:
     - "Content-Type: application/x-www-form-urlencoded"
    body: cOpcion=getDetalleReferencia&cLineaReferencia=121140858799880534337181289
  - name: WSINGRESOS - RECIBOPAGO
    method: POST
    url: https://srvshyweb.yucatan.gob.mx/cgi-bin/wspd_cgi.sh/WService=wsingresos/internet/servicios/wsRecibosPagosWeb.r
    __dangerous__insecure: true
    maxResponseTime: 2000
    headers:
     - "Content-Type: application/x-www-form-urlencoded"
    body: cOpcion=obtenerDetalleReferencia&cLineaReferencia=121140858799880534337181289
  - name: WSINGRESOS - GENERICO
    method: POST
    url: https://srvshyweb.yucatan.gob.mx/cgi-bin/wspd_cgi.sh/WService=wsingresos/internet/servicios/wsGenericoPagosWeb.r
    __dangerous__insecure: true
    maxResponseTime: 2000
    expectedStatusCodes:
     - 200
    headers:
     - "Content-Type: application/x-www-form-urlencoded"
    body: cLineaReferencia=121140858799880534337181289&cOpcion=getDetalleReferencia


assignees:
  - aafyyuc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://aafy.yucatan.gob.mx/imagen/favicon_.svg
  name: AAFY Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status Page AAFY
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
