# Change these first
owner: aafyyuc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AAFY PDP
    url: https://pagos.yucatan.gob.mx
  - name: AAFY Referenciados
    url: https://pagosreferencia.yucatan.gob.mx
  - name: AAFY Home
	  url: https://aafy.yucatan.gob.mx
    
assignees:
  - aafyyuc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://aafy.yucatan.gob.mx/imagen/favicon_.svg
  name: AAFY Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status Page AAFY
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
